# Create full conda environment for development, including some useful tools
name: python-testing
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - ipython
  - numpy
  - matplotlib
  - mypy
  - pandas>=0.24.2
  - pylint
  - pytest>=2.4
  - pytest-cov
  - pytest-flake8
  - pytest-mpl
  - pytest-runner
  - vcrpy
